### ISSUE TITLE
Please add a license to the repo

### ISSUE THREAD

**Issue by mbrukman** [vrischmann/cassandredis#1]
Thank you for creating and releasing this project! Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Thanks!

**Comment by vrischmann** [comment]
Hey,

yeah I'll add a license. Didn't expect this repository to ever be used, it's mostly dead now :)
I'll release it under the MIT license.

**Comment by vrischmann** [comment]
Fixed by 81644bdf656171643bfcb5b0a6f65da1a8879394
